# Site settings
title: Mingyue Blog
SEOTitle: 明月的博客 | mingyue5826 Blog
header-img: img/root/home-bg-fj.jpg
email:  1441656607@qq.com
description: "测试 | 明月，Java & Linux，test | 这里是 @mingyue5826 明月 的个人博客，与你一起发现更大的世界。"
keyword: "明月, Mingyue,  @mingyue5826, 明月的博客, mingyue5826 Blog, 博客, 个人网站, Java, Linux"
url: "http://blog.ming5826.xyz"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
zhihu_username:     mingyue5826
github_username:    ming5826
#linkedin_username:    
#weibo_username:    
twitter_username:   mingyue5826
#facebook_username:  

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: false                           # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# gitalk settings
gitalk:
   enable: true
   owner: ming5826
   repo: blog.ming5826.xyz
   clientID: 3eff99bd4686f472c4a0
   clientSecret: 9aa96b3da1bbf60cf3ea155a42aaabaf5af6f981
   admin: ming5826

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# Analytics settings
# Baidu Analytics
#ba_track_id: 5e4a91c21c
#ba_track_id:8db676af20

# Google Analytics
ga_track_id: 'UA-120526213-1'            # Format: UA-xxxxxx-xx
ga_domain: auto

# Baidu Analytics
baidu_analytics: 'acf228f78e775a8f670ed54c440de345'

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: " When you look long into an abyss,the abyss looks into you<br> 当你凝视深渊时,深渊也在凝视你"
sidebar-avatar: https://images.cnblogs.com/cnblogs_com/mingyue5826/1435875/o_head.png      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: [
    {
        title: "然然的博客",
        href: "https://blog.tengshe789.tech/"
    }
]
